apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  labels:
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: 822677736859.dkr.ecr.eu-west-1.amazonaws.com/pjyshadow-vpkf/demoapp
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  ports:
  - nodePort: 31001
    targetPort: 8080
    port: 8080
    protocol: TCP
  selector:
    app: demo-app
  type: NodePort

